# The URL the site will be built for
base_url = "https://waseemR02.github.io"
title = "Waseem's Portfolio"
build_search_index = true
compile_sass = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 4 },
]

socials = [
    { name = "github", url = "https://github.com/waseemr02/", icon = "github" },
    { name = "email", url = "mailto:waseem.riaz.9999@gmail.com", icon = "email"},
]

mathjax = true
mathjax_dollar_inline_enable = true
